### PR TITLE
#28 [BUG]: AddList handleSubmit is synchronous but contains an unresolved Promise

### LINKED ISSUE #28: [BUG]: AddList handleSubmit is synchronous but contains an unresolved Promise
### Description 
Our `handleSubmit` in the `AddList.jsx` file is not using `async`/`await` but uses an async function. We then check the returned promise in an if statement which is always true.

### Related issue
https://github.com/the-collab-lab/tcl-66-smart-shopping-list/issues/4

### Steps to reproduce
1. In the `AddList.jsx` file, `console.log` the value stored in `newList`.
2. Create a new shopping list.
3. See that it is a promise.
4. Promises are an object which always evaluate to true.

Alternatively:
1. Make `handleSubmit` asynchronous and `await` the `createList` function.
2. Create a new shopping list.
3. See that you get a message indicating the list was not created but your new list appears anyway and saves in the database.

### Expected behavior
The response in our app should depend on whether or not the `createList` function creates a list successfully.

### Platform
 - Device: Windows 11 PC
 - OS: Windows 11
 - Browser: Chrome

### Additional context
When you're using an asynchronous function you should use it inside another asynchronous function unless it doesn't matter whether or not it was successful.

### PR DESCRIPTION
**Pull request by StefieCaff**
Update `createList` in `firebase.js`
- Add `if` block to the list creation logic that `returns true` if the list is created otherwise `returns false`.

Update `handleSubmit` in `AddList.jsx`
- Make `handleSubmit` asynchronous and `await` the `createList` function.

## Description
In `firebase.js` `createList` is an asynchronous function, in `AddList.jsx` `handleSubmit` was calling it without `async await`. An async function needs to be handled by an async function(https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous). Without the `if` statement, the `newList` variable was returning as undefined (case 1: with asynchronous logic)  or as a promise ( case2: without asynchronous logic).  Either way, the database was creating the list. Since the `handleSubmit` logic was based on if `newList` existed the function continued to run as if the it was created properly. In the first case, the list was added but the user was alerted it was not, and there was no navigation. In the second case, the list was added the user was alerted and navigated, but the variable was an unresolved promise.

With this refactor, `createList()` will send handleSubmit() a true or a false, if the list is created or not, respectively. The proper messages and error handling will run as expected and the variable will be assigned correctly. By adding this logic to createList() the the `async` `await` syntax can be added to properly handle the asynchronous `createList` function.

## Related Issues

closes #28 
related to issue #4 

## Type of Changes

bug-fix

### Before
- Asynchronous `handleSubmit`
async bug

- Non Asynchronous `handleSubmit`
assync bug2

### After
async fix

## Testing Steps / QA Criteria

 * open branch sc-issue-28-bug-fix
 * add console.log to handleSubmit function at line 17 `console.log(newList)`
 * run npm start
 * sign in and navigate to home if not there
 * add a new list
 * check that the message says the list is made and navigate to the list page
 * check that the console prints true

### CODE REVIEW

File: src/components/AddList.jsx [hunk 1]
```diff
@@ -9,11 +9,12 @@ export default function AddList({ setListPath }) {
 	const navigate = useNavigate();
 	const { user } = useAuth();
 
-	const handleSubmit = (event) => {
-		event.preventDefault();
+	const handleSubmit = async (e) => {
+		e.preventDefault();
```
Comment (3campos) [inline src/components/AddList.jsx:13]: Nice attention to detail here by changing "event.preventDefault()" to "e.preventDefault()" for the sake of consistency. The rest of our application uses "e" to represent "event". Good call!

**Review by 3campos — APPROVED** [review]
@StefieCaff, great job identifying this problem! Your explanation helped me understand your changes. I ran your branch locally according to your instructions and everything works as expected, including the console.log reading "true" for newList. 

One last thing that is not a blocker: you have comments on the firebase.js file (line 123) and the addList file (line 17). In my view, these comments are helpful. If you meant to take them out though, go ahead remove them before you merge your PR. It's fine either way with me. Your call! 😄
